#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import process from "node:process";

import { FILE_NAMES } from "./constants.js";
import { generateFromPreset, generateFromProject, getDefaultThemeContract, writeCollections } from "./generator.js";
import { loadProjectSource } from "./project.js";
import { applyThemeDeclarationsToContract } from "./theme-contract.js";
import { renderThemeCss } from "./theme-css.js";
import { upsertManagedThemeBlock } from "./theme-files.js";
import { decodeThemePayload } from "./theme-payload.js";

function printUsage() {
  console.log(`Usage:
  node ./src/cli.js --preset <code> --out <dir> [--base base] [--template next]
  node ./src/cli.js --project <path> --out <dir>
  node ./src/cli.js theme css --project <path>
  node ./src/cli.js theme apply --project <path> --payload <base64url>

Options:
  --preset    shadcn preset code, for example bdvx03LE
  --project   existing shadcn project directory
  --out       output directory for generated collections
  --base      optional shadcn base passed during preset hydration (default: base)
  --template  optional shadcn template passed during preset hydration (default: next)
  --payload   serialized theme payload generated by the Figma plugin
`);
}

function parseArgs(argv) {
  const args = {};
  for (let index = 0; index < argv.length; index += 1) {
    const current = argv[index];
    if (!current.startsWith("--")) {
      continue;
    }

    const key = current.slice(2);
    const next = argv[index + 1];
    if (!next || next.startsWith("--")) {
      args[key] = true;
      continue;
    }

    args[key] = next;
    index += 1;
  }
  return args;
}

function buildProjectThemeContract(projectDir) {
  const projectSource = loadProjectSource(path.resolve(projectDir));
  const baseContract = getDefaultThemeContract();
  const contract = applyThemeDeclarationsToContract(baseContract, projectSource.declarations, {
    fonts: projectSource.fonts,
  });

  return {
    projectSource,
    contract,
  };
}

function runThemeCommand(argv) {
  const subcommand = argv[0];
  const args = parseArgs(argv.slice(1));

  if (args.help || !subcommand) {
    printUsage();
    process.exit(args.help ? 0 : 1);
  }

  if (!args.project) {
    throw new Error("Theme commands require --project <path>.");
  }

  if (subcommand === "css") {
    const { contract } = buildProjectThemeContract(args.project);
    process.stdout.write(renderThemeCss(contract));
    return;
  }

  if (subcommand === "apply") {
    if (!args.payload) {
      throw new Error("theme apply requires --payload <base64url>.");
    }

    const { projectSource } = buildProjectThemeContract(args.project);
    const payload = decodeThemePayload(args.payload);
    const nextCss = upsertManagedThemeBlock(projectSource.css, renderThemeCss(payload.contract));
    fs.writeFileSync(projectSource.cssPath, nextCss, "utf8");
    console.log(`Updated ${projectSource.cssPath}`);
    return;
  }

  throw new Error(`Unknown theme subcommand "${subcommand}".`);
}

async function main() {
  const argv = process.argv.slice(2);
  if (argv[0] === "theme") {
    runThemeCommand(argv.slice(1));
    return;
  }

  const args = parseArgs(argv);

  if (args.help || (!args.preset && !args.project)) {
    printUsage();
    process.exit(args.help ? 0 : 1);
  }

  if (args.preset && args.project) {
    throw new Error("Choose either --preset or --project, not both.");
  }

  const outputDir = args.out ? path.resolve(args.out) : path.resolve(process.cwd(), "generated");
  const result = args.preset
    ? generateFromPreset(args.preset, {
        base: args.base,
        template: args.template,
      })
    : generateFromProject(path.resolve(args.project));

  writeCollections(outputDir, result);

  console.log(`Wrote ${Object.keys(result.files).length + 1} files to ${outputDir}`);
  console.log(`- ${FILE_NAMES.manifest}`);
  for (const fileName of Object.keys(result.files)) {
    console.log(`- ${fileName}`);
  }
}

main().catch((error) => {
  console.error(error.message);
  process.exit(1);
});
