export const FILE_NAMES = {
  tailwind: "1. TailwindCSS.tokens.json",
  theme: "2. Theme.tokens.json",
  modeLight: "3. Mode.Light.tokens.json",
  modeDark: "3. Mode.Dark.tokens.json",
  customMobile: "4. Custom.Mobile.tokens.json",
  customDesktop: "4. Custo.Desktop.tokens.json",
  iconLibrary: "5. Icon Library.tokens.json",
  manifest: "manifest.json",
};

export const MANAGED_THEME_BLOCK = {
  start: "/* shadcn-theme:start */",
  end: "/* shadcn-theme:end */",
};

export const BLUEPRINT_FILES = [
  FILE_NAMES.tailwind,
  FILE_NAMES.theme,
  FILE_NAMES.modeLight,
  FILE_NAMES.modeDark,
  FILE_NAMES.customMobile,
  FILE_NAMES.customDesktop,
  FILE_NAMES.iconLibrary,
];

export const THEME_COLOR_SLOTS = [
  "accent",
  "accent-foreground",
  "background",
  "border",
  "card",
  "card-foreground",
  "chart-1",
  "chart-2",
  "chart-3",
  "chart-4",
  "chart-5",
  "destructive",
  "destructive-foreground",
  "foreground",
  "input",
  "muted",
  "muted-foreground",
  "popover",
  "popover-foreground",
  "primary",
  "primary-foreground",
  "ring",
  "secondary",
  "secondary-foreground",
  "sidebar",
  "sidebar-accent",
  "sidebar-accent-foreground",
  "sidebar-border",
  "sidebar-foreground",
  "sidebar-primary",
  "sidebar-primary-foreground",
  "sidebar-ring",
];

export const MODE_BASE_SLOTS = [
  "accent",
  "accent-foreground",
  "background",
  "border",
  "card",
  "card-foreground",
  "chart-1",
  "chart-2",
  "chart-3",
  "chart-4",
  "chart-5",
  "destructive",
  "destructive-foreground",
  "foreground",
  "input",
  "muted",
  "muted-foreground",
  "popover",
  "popover-foreground",
  "primary",
  "primary-foreground",
  "ring",
  "ring-offset",
  "secondary",
  "secondary-foreground",
  "sidebar",
  "sidebar-accent",
  "sidebar-accent-foreground",
  "sidebar-border",
  "sidebar-foreground",
  "sidebar-primary",
  "sidebar-primary-foreground",
  "sidebar-ring",
];

export const ALPHA_STEPS = [5, 10, 20, 30, 40, 50, 60, 70, 80, 90];

export const ICON_LIBRARY_LABELS = {
  lucide: "Lucide Icons",
  tabler: "Tabler Icons",
  hugeicons: "HugeIcons",
  phosphor: "Phosphor Icons",
  remix: "Remix Icon",
};

export const CUSTOM_LAYOUT_RULES = {
  mobile: {
    "container-padding-x": "spacing.4",
    "section-padding-y": "spacing.16",
    "section-title-gap-sm": "spacing.4",
    "section-title-gap-md": "spacing.4",
    "section-title-gap-lg": "spacing.4",
    "section-title-gap-xl": "spacing.5",
  },
  desktop: {
    "container-padding-x": "spacing.6",
    "section-padding-y": "spacing.24",
    "section-title-gap-sm": "spacing.4",
    "section-title-gap-md": "spacing.5",
    "section-title-gap-lg": "spacing.5",
    "section-title-gap-xl": "spacing.6",
  },
};

export const CUSTOM_TYPOGRAPHY_RULES = {
  mobile: {
    "heading-xl": { scale: "5xl", letterSpacing: -1.2 },
    "heading-lg": { scale: "4xl", letterSpacing: -0.9 },
    "heading-md": { scale: "3xl", letterSpacing: -0.75 },
    "heading-sm": { scale: "xl", letterSpacing: -0.5 },
  },
  desktop: {
    "heading-xl": { scale: "6xl", letterSpacing: -1.5 },
    "heading-lg": { scale: "5xl", letterSpacing: -1.2 },
    "heading-md": { scale: "4xl", letterSpacing: -0.9 },
    "heading-sm": { scale: "2xl", letterSpacing: -0.6 },
  },
};

export const RAW_COLOR_PREFIXES = [
  "amber",
  "base",
  "blue",
  "cyan",
  "emerald",
  "fuchsia",
  "gray",
  "green",
  "indigo",
  "lime",
  "mauve",
  "mist",
  "neutral",
  "olive",
  "orange",
  "pink",
  "purple",
  "red",
  "rose",
  "sky",
  "slate",
  "stone",
  "taupe",
  "teal",
  "violet",
  "yellow",
  "zinc",
];
